title: "Skokie in Motion"
event_date: "August 29, 2015"
baseurl: ""
permalink : /posts/:title
contacts: mjacobsen@skokielibrary.info;mshah@skokielibrary.info
exclude: [README.md, gulpfile.js, package.json, node_modules]
