title: "Skokie in Motion"
subtitle: "Skokie's only library film festival"
event_date: "August 29, 2015"
baseurl: ""
permalink : /posts/:title
contacts: mjacobsen@skokielibrary.info;mshah@skokielibrary.info
exclude: [README.md, bower.json, bower_components, scss, config.rb, working]
